
package com.hzfc.soar.zfbz.byfz.websupport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ByfzwwWebService", targetNamespace = "http://soar.hzfc.com/byfzwebservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ByfzwwWebService {


    /**
     * 
     * @param cqr
     * @param cqzbh
     * @param ywlb
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkForAccept", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.CheckForAccept")
    @ResponseWrapper(localName = "checkForAcceptResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.CheckForAcceptResponse")
    public String checkForAccept(
        @WebParam(name = "ywlb", targetNamespace = "")
        int ywlb,
        @WebParam(name = "cqzbh", targetNamespace = "")
        String cqzbh,
        @WebParam(name = "cqr", targetNamespace = "")
        String cqr);

    /**
     * 
     * @param keytype
     * @param keyword
     * @param jsdw
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryForXfbyyf", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.QueryForXfbyyf")
    @ResponseWrapper(localName = "queryForXfbyyfResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.QueryForXfbyyfResponse")
    public String queryForXfbyyf(
        @WebParam(name = "jsdw", targetNamespace = "")
        String jsdw,
        @WebParam(name = "keytype", targetNamespace = "")
        int keytype,
        @WebParam(name = "keyword", targetNamespace = "")
        String keyword);

    /**
     * 
     * @param fczh
     * @param fwzl
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sfblByyf", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.SfblByyf")
    @ResponseWrapper(localName = "sfblByyfResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.SfblByyfResponse")
    public Boolean sfblByyf(
        @WebParam(name = "fczh", targetNamespace = "")
        String fczh,
        @WebParam(name = "fwzl", targetNamespace = "")
        String fwzl);

    /**
     * 
     * @param fwzl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBymzyfBzqx", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.GetBymzyfBzqx")
    @ResponseWrapper(localName = "getBymzyfBzqxResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.GetBymzyfBzqxResponse")
    public String getBymzyfBzqx(
        @WebParam(name = "fwzl", targetNamespace = "")
        String fwzl);

    /**
     * 
     * @param keytype
     * @param keyword
     * @param sqr
     * @param ywlb
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryForJfbyfz", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.QueryForJfbyfz")
    @ResponseWrapper(localName = "queryForJfbyfzResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.QueryForJfbyfzResponse")
    public String queryForJfbyfz(
        @WebParam(name = "ywlb", targetNamespace = "")
        int ywlb,
        @WebParam(name = "sqr", targetNamespace = "")
        String sqr,
        @WebParam(name = "keytype", targetNamespace = "")
        int keytype,
        @WebParam(name = "keyword", targetNamespace = "")
        String keyword);

    /**
     * 
     * @param fczh
     * @param fwzl
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sfbzqxn", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.Sfbzqxn")
    @ResponseWrapper(localName = "sfbzqxnResponse", targetNamespace = "http://soar.hzfc.com/byfzwebservice", className = "com.hzfc.soar.zfbz.byfz.websupport.SfbzqxnResponse")
    public Boolean sfbzqxn(
        @WebParam(name = "fczh", targetNamespace = "")
        String fczh,
        @WebParam(name = "fwzl", targetNamespace = "")
        String fwzl);

}
