
package com.hzfc.soar.zfbz.byfz.websupport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "byfzwwWebService", targetNamespace = "http://soar.hzfc.com/byfzwebservice", wsdlLocation = "http://172.16.100.91:80/spi/byfzwebservice?wsdl")
public class ByfzwwWebService_Service
    extends Service
{

    private final static URL BYFZWWWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BYFZWWWEBSERVICE_EXCEPTION;
    private final static QName BYFZWWWEBSERVICE_QNAME = new QName("http://soar.hzfc.com/byfzwebservice", "byfzwwWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.100.91:80/spi/byfzwebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BYFZWWWEBSERVICE_WSDL_LOCATION = url;
        BYFZWWWEBSERVICE_EXCEPTION = e;
    }

    public ByfzwwWebService_Service() {
        super(__getWsdlLocation(), BYFZWWWEBSERVICE_QNAME);
    }

    public ByfzwwWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BYFZWWWEBSERVICE_QNAME, features);
    }

    public ByfzwwWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, BYFZWWWEBSERVICE_QNAME);
    }

    public ByfzwwWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BYFZWWWEBSERVICE_QNAME, features);
    }

    public ByfzwwWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ByfzwwWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ByfzwwWebService
     */
    @WebEndpoint(name = "ByfzwwWebServiceImplPort")
    public ByfzwwWebService getByfzwwWebServiceImplPort() {
        return super.getPort(new QName("http://soar.hzfc.com/byfzwebservice", "ByfzwwWebServiceImplPort"), ByfzwwWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ByfzwwWebService
     */
    @WebEndpoint(name = "ByfzwwWebServiceImplPort")
    public ByfzwwWebService getByfzwwWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soar.hzfc.com/byfzwebservice", "ByfzwwWebServiceImplPort"), ByfzwwWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BYFZWWWEBSERVICE_EXCEPTION!= null) {
            throw BYFZWWWEBSERVICE_EXCEPTION;
        }
        return BYFZWWWEBSERVICE_WSDL_LOCATION;
    }

}
